### ISSUE TITLE
Logging tweaks

### ISSUE THREAD

**Issue by alexishachemi** [mathematisse/Project-E#14]
- Global variable fix
- warning fixes

**Comment by LeoWherle** [comment]
#5 This could maybe be part of the tweaks, changing the enums to be LOG_ERROR instead of ERROR

**Comment by alexishachemi** [comment]
> #5 This could maybe be part of the tweaks, changing the enums to be LOG_ERROR instead of ERROR

I'll reopen the branch to work on it. It probably won't use the proposed names as this would clash with the logging macro.
```cpp
#define LOG_ERROR(message) LOG(logging::Level::ERROR, message)
```
